apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-service-insider-configmap
data:
  CLUSTER: "azure"
  PORT: "80"
  RING: "insider"
  TAG: 20210608T021444Z # {"$imagepolicy": "flux-system:hello-service-insider:tag"}
