apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../base/hello-service/main
    - ../base/hello-service/insider
    - hello-service-insider-configmap.yaml
    - hello-service-main-configmap.yaml
patchesStrategicMerge:
    - hello-service-insider-release.yaml
    - hello-service-main-release.yaml
