---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
    name: hello-service-insider
    namespace: flux-system
spec:
    image: tpark.azurecr.io/hello-service-insider
    secretRef:
        name: acr-secret
    interval: 1m0s
