# this is overlaid on top of ../base/hello-service/main
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: hello-service-main
    namespace: default
spec:
    values:
        service:
            name: hello-service-main
            dns: hello-main-gcp.contoso.com
            port: 80
        port: 80
        tls:
            secret: contoso-app-tls
        replicas: 4
