apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../base/hello-service/main
    - hello-service-main-configmap.yaml
patchesStrategicMerge:
    - hello-service-main-release.yaml
