---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
    name: hello-service-main
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: hello-service-main
    policy:
        alphabetical:
            order: asc
